### ISSUE TITLE
Broken link to tar

### ISSUE THREAD

**Issue by edloginova** [nicolay-r/ARElight#47]
Hi,

The link from the documentation to [nicolay-r-arelight-0.1.1.tar](https://drive.google.com/u/0/uc?id=1hd6EOcN5haEJM0dp_sdsNCX36lGG-y8Y&export=download&confirm=t) appears to be broken. It returns:
```
404. That’s an error.

The requested URL was not found on this server. That’s all we know.
```

**Comment by nicolay-r** [comment]
Hello @edloginova . I see, this happens due to the Google cloud subscription cancellation. I will update the link in short and let you know once it will be available. Thanks!

**Comment by nicolay-r** [comment]
@edloginova, here is an update link to the image:
https://disk.yandex.ru/d/XXJUXEeaJbqNbA
